Add failing test for sign in with multiple attrs
halogenandtoast/monban pull request #55
Opened 2016-11-07 00:20 UTC by graysonwright

This is a failing test case to reproduce the error referenced in #54. We should close that issue in favor of this one.

## Problem

The recommended implementation for sign in by email or username throws an error when looking up the User record.

Stack trace:
```
  1) User signs in with username or password
     Failure/Error: params.to_h

     TypeError:
       wrong element type String at 0 (expected array)
     # ./lib/monban/param_transformer.rb:25:in `to_h'
     # ./lib/monban/param_transformer.rb:25:in `sanitized_params'
     # ./lib/monban/param_transformer.rb:15:in `to_h'
     # ./lib/monban.rb:66:in `transform_params'
     # ./lib/monban/configuration.rb:57:in `block in default_find_method'
     # ./lib/monban.rb:90:in `lookup'
     # ./lib/monban/controller_helpers.rb:105:in `authenticate_session'
     # ./spec/rails_app/app/controllers/multiple_attributes_sessions_controller.rb:6:in `create'
     # ./lib/monban/back_door.rb:30:in `call'
     # ./spec/features/user/user_signs_in_spec.rb:25:in `block (2 levels) in <top (required)>'
```

2016-11-07 00:37 UTC, graysonwright commented
@halogenandtoast The test passes on my local machine. Not sure what's going on - any ideas?

2016-11-07 02:11 UTC, halogenandtoast commented
@graysonwright can you provide version numbers for your local setup:

Ruby/Rails/OS and anything else that might be relevant.

2016-11-07 02:16 UTC, halogenandtoast requested changes

2016-11-07 02:16 UTC, halogenandtoast commented on spec/rails_app/app/controllers/multiple_attributes_sessions_controller.rb
> +      email_or_username: [:email, :email_or_username],
This is incorrect (and why the test case is failing). This should be:

```ruby
email_or_username: [:email, :username]
```

2016-11-12 02:18 UTC, graysonwright commented on spec/rails_app/app/controllers/multiple_attributes_sessions_controller.rb
> +      email_or_username: [:email, :email_or_username],
ah, thanks! Fixing it up...

2016-11-13 07:15 UTC, graysonwright commented
@halogenandtoast I think it's good to go.

2016-11-17 02:58 UTC, halogenandtoast commented
@graysonwright can you just do a small write up about your solution. I assume the problem is that the params were being transformed twice. Was that the case?

2016-11-21 07:14 UTC, halogenandtoast approved these changes

2017-02-20 20:16 UTC, graysonwright commented
@halogenandtoast As far as I can remember, yes - the params were being transformed twice.

It's been a while since I submitted this PR, and I've forgotten the exact details. But I remember that when the params were passed to the original `default_find_method`, they had already been transformed and were ready to submit directly to `Model.find_by`. Transforming them again broke the `find_by` call.

2022-04-20 15:42 UTC, closed without merging